// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCn_FQyGpBoYGhwpXgS8AYn5kXEcHbF8rI',
    appId: '1:1016203646131:web:4607eece5f00be8bd14cc6',
    messagingSenderId: '1016203646131',
    projectId: 'chat-app-46c44',
    authDomain: 'chat-app-46c44.firebaseapp.com',
    storageBucket: 'chat-app-46c44.appspot.com',
    measurementId: 'G-P0G2N7145G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJL2JjteShsg4pUJILU9Ijjb776ie0Mx0',
    appId: '1:1016203646131:android:3caebff4f8e4872ed14cc6',
    messagingSenderId: '1016203646131',
    projectId: 'chat-app-46c44',
    storageBucket: 'chat-app-46c44.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIJQTlhWXlvlQX8Yj-RRu-R3jfwPEIDJM',
    appId: '1:1016203646131:ios:2e848c6b43f84305d14cc6',
    messagingSenderId: '1016203646131',
    projectId: 'chat-app-46c44',
    storageBucket: 'chat-app-46c44.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIJQTlhWXlvlQX8Yj-RRu-R3jfwPEIDJM',
    appId: '1:1016203646131:ios:6a50ff1360540451d14cc6',
    messagingSenderId: '1016203646131',
    projectId: 'chat-app-46c44',
    storageBucket: 'chat-app-46c44.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
